disabled_rules:
  - multiple_closures_with_trailing_closure
  - todo
nesting:
  type_level: 4
trailing_comma:
  severity: warning
  mandatory_comma: true
custom_rules:
  check_localized_string_bundle:
    excluded:
      - "MovieCatalog/.*\\.swift"
    name: "Localized string bundle"
    regex: 'String\([^)]*localized:\s*(?:"{3}[\s\S]*?"{3}|"[^"]*")(?![^)]*bundle:\s*\.module)[^)]*\)'
    message: "Remember to refer to the correct localization bundle with `bundle: .module`"
    severity: warning
  check_localized_string_bundle_for_text:
    included:
      - "Packages/.*\\.swift"
    name: "Localized string bundle for Text()"
    regex: '[^\w]Text\(\s*(?:"{3}[\s\S]*?"{3}|"[^"]*")(?![^)]*bundle:\s*\.module)[^)]*\)'
    message: "Remember to refer to the correct localization bundle with `bundle: .module`"
    severity: warning
  models_must_conform_to_hashable:
    included:
      - Packages/1-Base/MovieModels
    name: "Struct Hashable Conformance"
    message: "All structs must conform to Hashable."
    regex: 'public\s+struct\s+[A-Za-z_]\w*(?:\s*<[^>{]*>)?\s*(?:\{|\s*:\s*(?![^{}]*(?:\bHashable\b))[^{]+\{)'
    severity: warning

